### ISSUE TITLE
How does this method deal with false negatives?

### ISSUE THREAD

**Issue by timothylimyl** [we1pingyu/CALD#4]
Hi Weiping,

The idea of your paper is sampling based off inconsistency of predictions comparing prediction made on raw images and augmented images. From your results, it seems promising in terms of improving the mAP on lesser data required. However, I was wondering whether is this improvement purely driven solely by an increase in precision? 

It seems that this method can query out informative information ONLY if the detection is made in the first place.

**Comment by we1pingyu** [comment]
您好，我已收到您的邮件。我将尽快给您回复。祝您心情愉快。

**Comment by timothylimyl** [comment]
assume inactivity. closing
