### ISSUE TITLE
LICENSE REQUEST

### ISSUE THREAD

**Issue by taindp98** [we1pingyu/CALD#6]
Hi, I hope this message finds you well. I am reaching out to request a license for this repo. I have been using and finding value in the project, and I would like to ensure that I am complying with any licensing requirements. Having a clear license in place will not only benefit me but also other users who may come across the project. It will provide clarity on how the project can be used, modified, and distributed, fostering a stronger collaboration community. If you haven't considered licensing the repository yet, I kindly request you consider choosing an open-source license that aligns with your project's goals and values. Popular open-source licenses include the MIT License, Apache License 2.0.

Thank you for your attention, and I look forward to your positive response.
Best regards.

**Comment by we1pingyu** [comment]
Done

**Comment by taindp98** [comment]
thank you so much!
